[build]
  command = "npm run build:frontend"
  publish = "dist"

# Environment variable during build
[build.environment]
  VITE_API_URL = "https://your-backend-url.com"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 