[build]
  command = "npm run build:frontend"
  publish = "dist"

# Environment variable during build
[build.environment]
  VITE_API_URL = "https://thoughtcloud-mentorship.netlify.app"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Add CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://thoughtcloud-mentorship.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Add a specific rule for OPTIONS preflight requests
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true
  conditions = {method = "OPTIONS"}
  [redirects.headers]
    Access-Control-Allow-Origin = "https://thoughtcloud-mentorship.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    Content-Type = "text/plain" 