import { DocumentData, QueryConstraint, Timestamp } from 'firebase/firestore';
export declare const COLLECTIONS: {
    USERS: string;
    MENTORS: string;
    MENTEES: string;
    SESSIONS: string;
    AVAILABILITY: string;
    RATINGS: string;
    PAYMENTS: string;
};
export declare const addDocument: (collectionName: string, data: any) => Promise<string>;
export declare const setDocument: (collectionName: string, id: string, data: any) => Promise<void>;
export declare const getDocument: <T>(collectionName: string, id: string) => Promise<T | null>;
export declare const getDocuments: <T>(collectionName: string, constraints?: QueryConstraint[]) => Promise<T[]>;
export declare const updateDocument: (collectionName: string, id: string, data: Partial<DocumentData>) => Promise<void>;
export declare const deleteDocument: (collectionName: string, id: string) => Promise<void>;
export declare const whereEqual: (field: string, value: any) => import("@firebase/firestore").QueryFieldFilterConstraint;
export declare const whereIn: (field: string, values: any[]) => import("@firebase/firestore").QueryFieldFilterConstraint;
export declare const orderByField: (field: string, direction?: "asc" | "desc") => import("@firebase/firestore").QueryOrderByConstraint;
export declare const limitResults: (n: number) => import("@firebase/firestore").QueryLimitConstraint;
export declare const timestampToMillis: (timestamp: Timestamp) => number;
export declare const millisToTimestamp: (millis: number) => Timestamp;
export declare const serverTimestamp: () => number;
